---
title: "Pacotes da linguagem R para análise de pesquisas realizadas com escala Likert"
documentclass: article
authors: 
    - name: Ariel Levy
      affiliations: 
        - name: Universidade Federal Fluminense
    - name: Luciane Ferreira Alcoforado
      affiliations: 
        - name: Academia da Força Aérea
    - name: Orlando Celso Longo
      affiliations: 
        - name: Universidade Federal Fluminense
    - name: Marcus Antonio Cardoso Ramalho
      affiliations: 
        - name: Universidade Federal Fluminense

format: pdf
abstract: "A escala Likert é uma das escalas mais utilizadas em pesquisas sociais e comportamentais para medir atitudes,
opiniões e percepções dos respondentes. Ela consiste em um conjunto de itens que apresentam afirmações sobre um
determinado tema e solicitam que os respondentes indiquem o seu grau de concordância ou discordância com cada
afirmação, usando uma escala de valores numéricos ou verbais. A análise dos dados coletados com a escala Likert requer o
uso de técnicas estatísticas adequadas para lidar com as características e as limitações dessa escala. A linguagem R oferece
diversos pacotes que facilitam e otimizam a análise de pesquisas realizadas com escala Likert, permitindo realizar desde
operações básicas até análises avançadas e visualizações interativas. Nesta apresentação, vamos abordar os principais
pacotes da linguagem R para análise de pesquisas realizadas com escala Likert, destacando as suas funcionalidades,
vantagens e desvantagens"
---

<!---
 Olá! Sugiro aceitar o trabalho somente se realizarem mudanças maiores. Essas mudanças estão relacionadas principalmente a redefinir o objetivo do trabalho, ou seja, é necessário pensar em como o uso do R permite a análise de pesquisas realizadas com escala Likert. Em outras palavras, como o uso do R pode impulsionar a linha de análise de pesquisas com escala Likert. É necessário também fazer uma proposta metodológica, por exemplo, sugerir quais pacotes são mais apropriados para começar com pesquisas baseadas em escala Likert, quais pacotes são para análise intermediária e quais para análise avançada, isto é, fazer uma classificação dos pacotes em relação aos seus potenciais. Finalmente, a partir da metodologia proposta na sugestão anterior, é necessário expor os desafios que ainda não foram abordados nos pacotes descritos, o que poderia ser uma fonte de desenvolvimento de novos pacotes de R. Muito obrigada! 
--->

## resumo

A escala Likert é uma das escalas mais utilizadas em pesquisas sociais e comportamentais para medir atitudes, opiniões
e percepções dos respondentes. Ela consiste em um conjunto de itens que apresentam aﬁrmações sobre um determinado
tema e solicitam que os respondentes indiquem o seu grau de concordância ou discordância com cada aﬁrmação, usando
uma escala de valores numéricos ou verbais, Rensis (1932). A análise dos dados coletados com a escala Likert requer o
uso de técnicas estatísticas adequadas para lidar com as características e as limitações dessa escala. A linguagem R oferece
diversos pacotes que facilitam e otimizam a análise de pesquisas realizadas com escala Likert, permitindo realizar desde
operações básicas até análises avançadas e visualizações interativas.
Nesta apresentação, vamos abordar os principais pacotes da linguagem R para análise de pesquisas realizadas com
escala Likert, destacando as suas funcionalidades, vantagens e desvantagens. Vamos também apresentar alguns exemplos
práticos de uso desses pacotes e as principais demandas dos pesquisadores sobre o uso dessa ferramenta.

## Objetivos

Neste trabalho, busca-se apresentar de maneira concisa os pacotes essenciais da linguagem R empregados na análise de pesquisas baseadas na escala Likert, destacando suas funcionalidades e aplicabilidades. Além disso, pretende-se abordar as vantagens e desvantagens inerentes a cada pacote, proporcionando uma visão imparcial das capacidades disponíveis para pesquisadores e analistas. Em paralelo, serão fornecidos exemplos concretos de como esses pacotes podem ser eficazmente utilizados na análise de dados de pesquisas com escala Likert. Por fim, o trabalho visa identificar as demandas primordiais dos pesquisadores nessa área, com o intuito de contribuir para o desenvolvimento contínuo de recursos e ferramentas que atendam às necessidades da comunidade acadêmica e de pesquisa, promovendo avanços na análise de respostas na escala Likert.

## Metodologia

## Discussão

## Conclusão
